spring.application.name=wallet-server

server.port= 8086
eureka.client.service-url.defaultZone=http://localhost:8082/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# H2 Database
spring.datasource.url=jdbc:h2:file:./data/authdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# H2 Console
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled =true
spring.h2.console.path =/h2-console