spring.application.name=api-gateway

server.port = 8080
eureka.client.service-url.defaultZone=http://discovery-server:8082/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Auth Service/**
spring.cloud.gateway.server.webflux.routes[0].id=auth-server
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVER
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# Wallet Service
spring.cloud.gateway.server.webflux.routes[1].id=wallet-server
spring.cloud.gateway.server.webflux.routes[1].uri=lb://WALLET-SERVER
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/wallet/**

# Payment Service
spring.cloud.gateway.server.webflux.routes[2].id=payment-server
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PAYMENT-SERVER
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/payment/**